name = "lox"
description = "Shiny new project"
version = "0.0.0"

authors = ["Jon Andrew"]
maintainers = ["Jon Andrew <jonfandrew@duck.com>"]
maintainers-logins = ["docandrew"]

executables = ["lox"]
